name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
         - name: Checkout repo
           uses: actions/checkout@v2

         - name: Run prismacloud
           id: prismacloud
           uses: bridgecrewio/checkov-action@master 
           env:
            PRISMA_API_URL: https://api.prismacloud.io
           with:
             api-key: ${{ secrets.BC_API_KEY }}
