name: Prisma Cloud IaC
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
         - name: Run Prisma Cloud
           id: Prisma Cloud
           uses: bridgecrewio/checkov-action@master 
           env:
            PRISMA_API_URL: https://api.prismacloud.io
           with:
             api-key: ${{ secrets.BC_API_KEY }}
